export type PreRollArtwork = {
  readonly id: string;
  readonly name: string;
  readonly edition: string;
  readonly collection: string;
  readonly description: string;
  readonly src: `/media/pre-rolls/${string}.webp`;
  readonly alt: string;
  readonly shape: "portrait" | "square";
};

export const PRE_ROLL_ARTWORKS = [
  {
    id: "cereal-milk-title",
    name: "Cereal Milk",
    edition: "1g infused pre-roll · Flower · Live rosin · Diamonds",
    collection: "Rose Gold Connoisseur Series",
    description: "Cereal Milk brings a creamy strain profile known for sweet milk and vanilla notes to Presidential's live-rosin infusion. Flower, live rosin, and diamonds make this a choice for connoisseurs who want the rosin recipe in a finished roll. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/cereal-milk-title.webp",
    alt: "Presidential Cereal Milk 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "cereal-milk",
    name: "Cereal Milk",
    edition: "1g infused pre-roll · Flower · Live rosin · Diamonds",
    collection: "Rose Gold Connoisseur Series",
    description: "Cereal Milk brings a creamy strain profile known for sweet milk and vanilla notes to Presidential's live-rosin infusion. Flower, live rosin, and diamonds make this a choice for connoisseurs who want the rosin recipe in a finished roll. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/cereal-milk.webp",
    alt: "Presidential Cereal Milk 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "blue-dream",
    name: "Blue Dream",
    edition: "1g infused pre-roll · Flower · Live resin · Diamonds",
    collection: "Gold Strain Series",
    description: "Blue Dream's familiar blueberry character meets earthy pine in this flower, live resin, and diamonds combination. It is a natural pick for people who enjoy berry notes with a recognizable cannabis finish. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/blue-dream.webp",
    alt: "Presidential Blue Dream 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "blue-raspberry",
    name: "Blue Raspberry",
    edition: "1g infused pre-roll · Flower · Distillate · Kief",
    collection: "Silver Flavor Series",
    description: "Blue Raspberry puts its namesake berry flavor at the front of Presidential's flower, distillate, and kief recipe. Choose it when you want a fruit-flavored Moon Rock with the substance of infused cannabis flower. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/blue-raspberry.webp",
    alt: "Presidential Blue Raspberry 1g Moon Rock pre-roll product",
    shape: "square",
  },
  {
    id: "cap-junky",
    name: "Cap Junky",
    edition: "1g infused pre-roll · Flower · Live resin · Diamonds",
    collection: "Gold Strain Series",
    description: "Cap Junky brings a gassy strain profile with citrus zest and pine to the Presidential and Trendi collaboration. Flower infused with liquid live resin and finished with diamonds gives fuel-and-citrus fans a ready-rolled way to explore this selection. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/cap-junky.webp",
    alt: "Presidential Cap Junky 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "cherry-gelato",
    name: "Cherry Gelato",
    edition: "1g infused pre-roll · Flower · Distillate · Kief",
    collection: "Gold Strain Series",
    description: "Cherry Gelato pairs a sweet cherry and creamy Gelato profile with Presidential's Rove collaboration. Cannabis flower, distillate, and kief bring the infusion, making this a selection for people drawn to fruit with a rounded, creamy character. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/cherry-gelato.webp",
    alt: "Presidential Cherry Gelato 1g Moon Rock pre-roll product",
    shape: "square",
  },
  {
    id: "galactic-gas",
    name: "Galactic Gas",
    edition: "1g infused pre-roll · Flower · Live resin · Diamonds",
    collection: "Gold Strain Series",
    description: "Galactic Gas is for the fuel-and-spice enthusiast: its strain profile is reported as pungent gas, pine, and spicy herbs. Flower, live resin, and diamonds bring that named selection into Presidential's infused Moon Rock format. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/galactic-gas.webp",
    alt: "Presidential Galactic Gas 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "garlic-cookies-announcement",
    name: "Garlic Cookies",
    edition: "1g infused pre-roll · Flower · Distillate · Kief",
    collection: "Presidential Line collaboration",
    description: "Garlic Cookies brings Nature's Chemistry flower together with distillate and kief. Its savory garlic, earthy, and diesel profile makes it a distinctive choice for consumers who prefer pungent cannabis over fruit-forward selections. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/garlic-cookies-announcement.webp",
    alt: "Presidential Garlic Cookies 1g Moon Rock pre-roll product",
    shape: "square",
  },
  {
    id: "garlic-cookies",
    name: "Garlic Cookies",
    edition: "1g infused pre-roll · Flower · Distillate · Kief",
    collection: "Presidential Line collaboration",
    description: "Garlic Cookies brings Nature's Chemistry flower together with distillate and kief. Its savory garlic, earthy, and diesel profile makes it a distinctive choice for consumers who prefer pungent cannabis over fruit-forward selections. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/garlic-cookies.webp",
    alt: "Presidential Garlic Cookies 1g Moon Rock pre-roll product",
    shape: "square",
  },
  {
    id: "ghost-haze-train",
    name: "Ghost Train Haze",
    edition: "1g infused pre-roll · Flower · Distillate · Kief",
    collection: "Presidential Line collaboration",
    description: "Ghost Train Haze combines Nature's Chemistry flower with distillate and a kief finish. Reported citrus, pine, and spice give this Haze selection its appeal to people who favor sharp, herbal cannabis aromas. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/ghost-haze-train.webp",
    alt: "Presidential Ghost Train Haze 1g Moon Rock pre-roll product",
    shape: "square",
  },
  {
    id: "gorilla-goo",
    name: "Gorilla Goo",
    edition: "1g infused pre-roll · Flower · Live resin · Distillate · Diamonds",
    collection: "Gold Strain Series",
    description: "Gorilla Goo's reported sour fuel, pine, and chocolate notes give it a rich, gassy character. This version combines flower, live resin, distillate, and diamonds for consumers who want a layered infusion around that robust strain profile. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/gorilla-goo.webp",
    alt: "Presidential Gorilla Goo 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "grape",
    name: "Grape",
    edition: "1g infused pre-roll · Flower · Distillate · Kief",
    collection: "Silver Flavor Series",
    description: "Grape brings a grape-led flavor to Presidential's flower, distillate, and kief combination. It is a straightforward choice for people who want a recognizable fruit flavor in a prepared Moon Rock roll. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/grape.webp",
    alt: "Presidential Grape 1g Moon Rock pre-roll product",
    shape: "square",
  },
  {
    id: "king-louis",
    name: "King Louis",
    edition: "1g infused pre-roll · Flower · Live resin · Diamonds",
    collection: "Gold Strain Series",
    description: "King Louis leans into the classic OG profile: pine, lemon, earth, and a pronounced fuel note. Flower infused with live resin and finished with diamonds makes it a selection for consumers who appreciate a traditional kush character. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/king-louis.webp",
    alt: "Presidential King Louis 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "nyc-diesel",
    name: "NYC Diesel",
    edition: "1g infused pre-roll · Flower · Live resin · Diamonds",
    collection: "Gold Strain Series",
    description: "NYC Diesel brings grapefruit-like citrus and unmistakable fuel notes to flower infused with live resin and finished with diamonds. Choose it for the contrast between a bright citrus nose and a deeper diesel character. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/nyc-diesel.webp",
    alt: "Presidential NYC Diesel 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "orange-push-pop",
    name: "Orange Push Pop",
    edition: "1g infused pre-roll · Flower · Live resin · Diamonds",
    collection: "Gold Strain Series",
    description: "Orange Push Pop combines Trendi flower, liquid live resin, and diamonds. Its reported creamy citrus profile makes this collaboration a match for consumers who enjoy rounded orange notes with their infused flower. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/orange-push-pop.webp",
    alt: "Presidential Orange Push Pop 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "papaya-punch",
    name: "Papaya Punch",
    edition: "1g infused pre-roll · Flower · Live resin · Diamonds",
    collection: "Gold Strain Series",
    description: "Papaya Punch brings a tropical fruit and berry profile to flower infused with live resin and finished with diamonds. This is the selection for people who gravitate toward juicy fruit character while still wanting Presidential's layered cannabis construction. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/papaya-punch.webp",
    alt: "Presidential Papaya Punch 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "peach-mango",
    name: "Peach Mango",
    edition: "1g infused pre-roll · Flower · Distillate · Kief",
    collection: "Silver Flavor Series",
    description: "Peach Mango brings together ripe peach and mango flavor in Presidential's flower, distillate, and kief recipe. Its tropical fruit character suits consumers who want a distinctly fruity infused roll. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/peach-mango.webp",
    alt: "Presidential Peach Mango 1g Moon Rock pre-roll product",
    shape: "square",
  },
  {
    id: "pineapple",
    name: "Pineapple",
    edition: "1g infused pre-roll · Flower · Distillate · Kief",
    collection: "Silver Flavor Series",
    description: "Pineapple centers the namesake tropical fruit flavor over cannabis flower infused with distillate and finished with kief. A fruit-led choice for consumers who like pineapple character in a ready-rolled Moon Rock. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/pineapple.webp",
    alt: "Presidential Pineapple 1g Moon Rock pre-roll product",
    shape: "square",
  },
  {
    id: "pink-cookies",
    name: "Pink Cookies",
    edition: "1g infused pre-roll · Flower · Live resin · Distillate · Diamonds",
    collection: "Gold Strain Series",
    description: "Pink Cookies is associated with a sweet vanilla profile balanced by earth and citrus. This version brings together flower, live resin, distillate, and diamonds for consumers who enjoy creamy strain character with a layered infusion. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/pink-cookies.webp",
    alt: "Presidential Pink Cookies 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "presidential-og",
    name: "Presidential (Classic)",
    edition: "1g infused pre-roll · Flower · Distillate · Kief",
    collection: "Gold Strain Series",
    description: "The original Presidential selection pairs cannabis flower with distillate and kief. Its reported earthy, mint, and floral character makes Classic a useful starting point for consumers who want the house Moon Rock recipe. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/presidential-og.webp",
    alt: "Presidential Presidential (Classic) 1g Moon Rock pre-roll product",
    shape: "square",
  },
  {
    id: "rainbow-belts",
    name: "Rainbow Belts",
    edition: "1g infused pre-roll · Flower · Live resin · Diamonds",
    collection: "Gold Strain Series",
    description: "Rainbow Belts balances sweet fruit and citrus with a diesel edge in its reported strain profile. Flower, live resin, and diamonds make it a choice for people who enjoy both fruity and gassy notes in the same selection. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/rainbow-belts.webp",
    alt: "Presidential Rainbow Belts 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "sfv-og",
    name: "SFV OG",
    edition: "1g infused pre-roll · Flower · Live resin · Diamonds",
    collection: "Gold Strain Series",
    description: "SFV OG brings lemon, pine, and earthy diesel character to Presidential's live-resin-and-diamonds recipe. It is a selection for consumers who appreciate the resinous citrus-and-pine side of the OG family. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/sfv-og.webp",
    alt: "Presidential SFV OG 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "skywalker",
    name: "Skywalker",
    edition: "1g infused pre-roll · Flower · Distillate · Kief",
    collection: "Gold Strain Series",
    description: "Skywalker pairs cannabis flower with Rove-formulated distillate and a kief finish. Rove describes its Skywalker profile through blueberry, tropical, and earthy notes, giving this collaboration a fruit-and-earth character to explore. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/skywalker.webp",
    alt: "Presidential Skywalker 1g Moon Rock pre-roll product",
    shape: "square",
  },
  {
    id: "strawberry",
    name: "Strawberry",
    edition: "1g infused pre-roll · Flower · Distillate · Kief",
    collection: "Silver Flavor Series",
    description: "Strawberry brings a sweet berry flavor to Presidential's flower, distillate, and kief recipe. Choose this fruit-forward selection when strawberry is the flavor you want in an infused roll. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/strawberry.webp",
    alt: "Presidential Strawberry 1g Moon Rock pre-roll product",
    shape: "square",
  },
  {
    id: "cosmic-cookies",
    name: "Cosmic Cookies",
    edition: "1g infused pre-roll · Flower · Live rosin · Diamonds",
    collection: "Rose Gold Connoisseur Series",
    description: "Cosmic Cookies combines cannabis flower, live rosin, and diamonds in Presidential's Rose Gold selection. Its appeal is the recipe itself: a hybrid selection with a live-rosin infusion, prepared for consumers who want to explore the connoisseur side of Moon Rocks. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/cosmic-cookies.webp",
    alt: "Presidential Cosmic Cookies 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "wedding-cake-title",
    name: "Wedding Cake",
    edition: "1g infused pre-roll · Flower · Live rosin · Diamonds",
    collection: "Rose Gold Connoisseur Series",
    description: "Wedding Cake brings a strain profile known for vanilla, sweetness, and earthy citrus to Presidential's Rose Gold recipe. Flower, live rosin, and diamonds make it a selection for people who enjoy creamy cannabis character and a rosin-based infusion. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/wedding-cake-title.webp",
    alt: "Presidential Wedding Cake 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
  {
    id: "wedding-cake",
    name: "Wedding Cake",
    edition: "1g infused pre-roll · Flower · Live rosin · Diamonds",
    collection: "Rose Gold Connoisseur Series",
    description: "Wedding Cake brings a strain profile known for vanilla, sweetness, and earthy citrus to Presidential's Rose Gold recipe. Flower, live rosin, and diamonds make it a selection for people who enjoy creamy cannabis character and a rosin-based infusion. One 1g Moon Rock pre-roll, prepared in rolling paper.",
    src: "/media/pre-rolls/wedding-cake.webp",
    alt: "Presidential Wedding Cake 1g Moon Rock pre-roll product",
    shape: "portrait",
  },
] as const satisfies readonly PreRollArtwork[];

export const FEATURED_PRE_ROLL_ARTWORK_IDS = [
  "galactic-gas",
  "cereal-milk-title",
  "blue-dream",
  "garlic-cookies-announcement",
  "pink-cookies",
  "skywalker",
] as const;
