export type PreRollArtwork = {
  readonly id: string;
  readonly name: string;
  readonly edition: string;
  readonly collection: string;
  readonly description: string;
  readonly src: `/media/pre-rolls/${string}.webp`;
  readonly alt: string;
  readonly shape: "portrait" | "square";
};

export const PRE_ROLL_ARTWORKS = [
  {
    id: "cereal-milk-title",
    name: "Cereal Milk",
    edition: "Title artwork",
    collection: "Rose Gold Connoisseur Series",
    description: "Orange, cream, and electric blue collide around the Cereal Milk pack, with the oversized flavor title finishing the composition like a poster headline.",
    src: "/media/pre-rolls/cereal-milk-title.webp",
    alt: "Cereal Milk Presidential Moon Rock Pre-Roll graphic with orange, cream, and blue cereal artwork",
    shape: "portrait",
  },
  {
    id: "cereal-milk",
    name: "Cereal Milk",
    edition: "Clean artwork",
    collection: "Rose Gold Connoisseur Series",
    description: "The alternate Cereal Milk treatment lets the package and its milk-and-cereal splash carry the full frame without the oversized title lockup.",
    src: "/media/pre-rolls/cereal-milk.webp",
    alt: "Alternate Cereal Milk Presidential Moon Rock Pre-Roll package graphic",
    shape: "portrait",
  },
  {
    id: "blue-dream",
    name: "Blue Dream",
    edition: "Collection artwork",
    collection: "Gold Strain Series",
    description: "A cool blue dreamscape lifts the pack above sculpted clouds, palms, and distant birds for one of the collection's calmest visual worlds.",
    src: "/media/pre-rolls/blue-dream.webp",
    alt: "Blue Dream Presidential Moon Rock Pre-Roll graphic above blue clouds and palm trees",
    shape: "portrait",
  },
  {
    id: "blue-raspberry",
    name: "Blue Raspberry",
    edition: "Collection artwork",
    collection: "Silver Flavor Series",
    description: "Blue Raspberry surrounds the cobalt package with frozen berry forms and a dark burst of icy blue and red texture.",
    src: "/media/pre-rolls/blue-raspberry.webp",
    alt: "Blue Raspberry Presidential Moon Rock Pre-Roll graphic with blue and red berry artwork",
    shape: "square",
  },
  {
    id: "cap-junky",
    name: "Cap Junky",
    edition: "Trendi collaboration artwork",
    collection: "Gold Strain Series",
    description: "Cap Junky sets black-and-gold packaging against sharp teal botanicals, faceted leaves, and a bold green title treatment.",
    src: "/media/pre-rolls/cap-junky.webp",
    alt: "Cap Junky Presidential and Trendi Moon Rock Pre-Roll graphic with teal botanical artwork",
    shape: "portrait",
  },
  {
    id: "cherry-gelato",
    name: "Cherry Gelato",
    edition: "Rove collaboration artwork",
    collection: "Gold Strain Series",
    description: "Cherry Gelato uses a saturated red pack, suspended cherries, teal particles, and a waffle-cone base to turn the flavor name into a vivid scene.",
    src: "/media/pre-rolls/cherry-gelato.webp",
    alt: "Cherry Gelato Presidential and Rove Moon Rock Pre-Roll graphic with cherries and teal particles",
    shape: "square",
  },
  {
    id: "galactic-gas",
    name: "Galactic Gas",
    edition: "Collection artwork",
    collection: "Gold Strain Series",
    description: "A violet moon, floating planets, and ribbons of neon cyan and magenta give Galactic Gas its deep-space identity.",
    src: "/media/pre-rolls/galactic-gas.webp",
    alt: "Galactic Gas Presidential Moon Rock Pre-Roll graphic with a moon and neon cosmic forms",
    shape: "portrait",
  },
  {
    id: "garlic-cookies-announcement",
    name: "Garlic Cookies",
    edition: "Announcement artwork",
    collection: "Presidential Line collaboration",
    description: "This supplied announcement edition pairs the black-and-green collaboration pack with a monochrome field of garlic and a prominent Coming Soon title.",
    src: "/media/pre-rolls/garlic-cookies-announcement.webp",
    alt: "Garlic Cookies Presidential collaboration announcement graphic with garlic artwork and Coming Soon text",
    shape: "square",
  },
  {
    id: "garlic-cookies",
    name: "Garlic Cookies",
    edition: "Clean artwork",
    collection: "Presidential Line collaboration",
    description: "The clean Garlic Cookies composition keeps the geometric collaboration pack centered inside a dramatic green field of garlic and leaves.",
    src: "/media/pre-rolls/garlic-cookies.webp",
    alt: "Garlic Cookies Presidential collaboration Moon Rock Pre-Roll graphic with green garlic artwork",
    shape: "square",
  },
  {
    id: "ghost-haze-train",
    name: "Ghost Haze Train",
    edition: "Collaboration artwork",
    collection: "Presidential Line collaboration",
    description: "Ghostly vapor curls around a railway beneath a full moon, building a cinematic night scene around the green collaboration pack.",
    src: "/media/pre-rolls/ghost-haze-train.webp",
    alt: "Ghost Haze Train Presidential collaboration Moon Rock Pre-Roll graphic with a moonlit railway",
    shape: "square",
  },
  {
    id: "gorilla-goo",
    name: "Gorilla Goo",
    edition: "Collection artwork",
    collection: "Gold Strain Series",
    description: "Gorilla Goo brings a roaring gorilla out of purple and teal powder clouds, framing the black pack with high-energy contrast.",
    src: "/media/pre-rolls/gorilla-goo.webp",
    alt: "Gorilla Goo Presidential Moon Rock Pre-Roll graphic with a purple and teal gorilla",
    shape: "portrait",
  },
  {
    id: "grape",
    name: "Grape",
    edition: "Collection artwork",
    collection: "Silver Flavor Series",
    description: "Clusters of purple grapes push through a teal-and-violet powder burst, matching the bright magenta face of the Grape pack.",
    src: "/media/pre-rolls/grape.webp",
    alt: "Grape Presidential Moon Rock Pre-Roll graphic with purple grapes and teal powder",
    shape: "square",
  },
  {
    id: "king-louis",
    name: "King Louis",
    edition: "Collaboration artwork",
    collection: "Gold Strain Series",
    description: "King Louis stands in front of a pale moon while red and teal plumes rise like a royal crest around the package.",
    src: "/media/pre-rolls/king-louis.webp",
    alt: "King Louis Presidential Moon Rock Pre-Roll graphic with a moon and red and teal plumes",
    shape: "portrait",
  },
  {
    id: "nyc-diesel",
    name: "NYC Diesel",
    edition: "Collection artwork",
    collection: "Gold Strain Series",
    description: "A green package cuts through black smoke, metallic forms, and moonlight in a composition with an unmistakably urban edge.",
    src: "/media/pre-rolls/nyc-diesel.webp",
    alt: "NYC Diesel Presidential Moon Rock Pre-Roll graphic with green smoke and a full moon",
    shape: "portrait",
  },
  {
    id: "orange-push-pop",
    name: "Orange Push Pop",
    edition: "Trendi collaboration artwork",
    collection: "Gold Strain Series",
    description: "Orange Push Pop turns the Trendi collaboration pack into the center of an orange, teal, and white frozen-pop explosion.",
    src: "/media/pre-rolls/orange-push-pop.webp",
    alt: "Orange Push Pop Presidential and Trendi Moon Rock Pre-Roll graphic with orange frozen-pop artwork",
    shape: "portrait",
  },
  {
    id: "papaya-punch",
    name: "Papaya Punch",
    edition: "Collection artwork",
    collection: "Gold Strain Series",
    description: "Papaya fruit, tropical leaves, orange flowers, and teal vapor gather beneath a moonlit package portrait.",
    src: "/media/pre-rolls/papaya-punch.webp",
    alt: "Papaya Punch Presidential Moon Rock Pre-Roll graphic with papaya, flowers, and a moon",
    shape: "portrait",
  },
  {
    id: "peach-mango",
    name: "Peach Mango",
    edition: "Collection artwork",
    collection: "Silver Flavor Series",
    description: "Soft coral fruit, dark palm fronds, and broad peach-colored powder strokes create a warm tropical frame for Peach Mango.",
    src: "/media/pre-rolls/peach-mango.webp",
    alt: "Peach Mango Presidential Moon Rock Pre-Roll graphic with tropical fruit and palm leaves",
    shape: "square",
  },
  {
    id: "pineapple",
    name: "Pineapple",
    edition: "Collection artwork",
    collection: "Silver Flavor Series",
    description: "Pineapple uses a vivid yellow pack, fresh fruit, teal foliage, and a sunburst of powder to create a bright tropical composition.",
    src: "/media/pre-rolls/pineapple.webp",
    alt: "Pineapple Presidential Moon Rock Pre-Roll graphic with pineapple and tropical foliage",
    shape: "square",
  },
  {
    id: "pink-cookies",
    name: "Pink Cookies",
    edition: "Collection artwork",
    collection: "Gold Strain Series",
    description: "Cookie pieces and candy-pink dust burst behind the package while teal palm shapes sharpen the contrast.",
    src: "/media/pre-rolls/pink-cookies.webp",
    alt: "Pink Cookies Presidential Moon Rock Pre-Roll graphic with cookies and pink and teal artwork",
    shape: "portrait",
  },
  {
    id: "presidential-og",
    name: "Presidential OG",
    edition: "Signature artwork",
    collection: "Gold Strain Series",
    description: "Presidential OG places the teal pack over a stylized Los Angeles boulevard, white palms, city towers, and a low classic car.",
    src: "/media/pre-rolls/presidential-og.webp",
    alt: "Presidential OG Moon Rock Pre-Roll graphic with a Los Angeles boulevard and classic car",
    shape: "square",
  },
  {
    id: "rainbow-belts",
    name: "Rainbow Belts",
    edition: "Collection artwork",
    collection: "Gold Strain Series",
    description: "A ribbon of rainbow candy wraps through smoke and orbiting planets around the deep red package.",
    src: "/media/pre-rolls/rainbow-belts.webp",
    alt: "Rainbow Belts Presidential Moon Rock Pre-Roll graphic with rainbow candy and planets",
    shape: "portrait",
  },
  {
    id: "sfv-og",
    name: "SFV OG",
    edition: "Collection artwork",
    collection: "Gold Strain Series",
    description: "SFV OG rises from pale clouds, moonlight, and a line of palms, with the orange title anchoring the cool green scene.",
    src: "/media/pre-rolls/sfv-og.webp",
    alt: "SFV OG Presidential Moon Rock Pre-Roll graphic with moonlight, clouds, and palm trees",
    shape: "portrait",
  },
  {
    id: "skywalker",
    name: "Skywalker",
    edition: "Rove collaboration artwork",
    collection: "Gold Strain Series",
    description: "Skywalker sends the collaboration pack into a deep blue asteroid field, surrounded by icy rock forms and distant planets.",
    src: "/media/pre-rolls/skywalker.webp",
    alt: "Skywalker Presidential and Rove Moon Rock Pre-Roll graphic in a blue asteroid field",
    shape: "square",
  },
  {
    id: "strawberry",
    name: "Strawberry",
    edition: "Collection artwork",
    collection: "Silver Flavor Series",
    description: "Ripe strawberries and red powder sweep across teal foliage, giving the scarlet Strawberry pack a rich botanical frame.",
    src: "/media/pre-rolls/strawberry.webp",
    alt: "Strawberry Presidential Moon Rock Pre-Roll graphic with strawberries and teal foliage",
    shape: "square",
  },
  {
    id: "cosmic-cookies",
    name: "Cosmic Cookies",
    edition: "Collection artwork",
    collection: "Rose Gold Connoisseur Series",
    description: "Cosmic Cookies floats through a dense violet universe of planets, nebulae, and electric light around the midnight-blue pack.",
    src: "/media/pre-rolls/cosmic-cookies.webp",
    alt: "Cosmic Cookies Presidential Moon Rock Pre-Roll graphic in a violet galaxy",
    shape: "portrait",
  },
  {
    id: "wedding-cake-title",
    name: "Wedding Cake",
    edition: "Title artwork",
    collection: "Rose Gold Connoisseur Series",
    description: "The Wedding Cake title edition layers the package over pink confection colors, jewel-like droplets, and flowing icing forms.",
    src: "/media/pre-rolls/wedding-cake-title.webp",
    alt: "Wedding Cake Presidential Moon Rock Pre-Roll title graphic with pink confection artwork",
    shape: "portrait",
  },
  {
    id: "wedding-cake",
    name: "Wedding Cake",
    edition: "Clean artwork",
    collection: "Rose Gold Connoisseur Series",
    description: "The clean Wedding Cake treatment removes the oversized title so the peach package, pink field, and liquid jewel details own the frame.",
    src: "/media/pre-rolls/wedding-cake.webp",
    alt: "Alternate Wedding Cake Presidential Moon Rock Pre-Roll graphic with pink and jeweled artwork",
    shape: "portrait",
  },
] as const satisfies readonly PreRollArtwork[];

export const FEATURED_PRE_ROLL_ARTWORK_IDS = [
  "galactic-gas",
  "cereal-milk-title",
  "blue-dream",
  "garlic-cookies-announcement",
  "pink-cookies",
  "skywalker",
] as const;
