import type { SeoRouteRecord, SeoRoutePath } from "./route-types";

export const MANDATORY_ROUTE_PATHS = [
  "/",
  "/moon-rocks",
  "/moon-pods",
  "/orbit",
  "/our-story",
  "/about",
  "/learn",
  "/learn/[guide]",
  "/find-us",
  "/contact",
] as const satisfies readonly SeoRoutePath[];

export const ROUTE_REGISTRY = [
  {
    id: "home",
    path: "/",
    kind: "brand_home",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 5,
    changeFrequency: "weekly",
    canonicalPath: "/",
    title: "Presidential Moon Rocks | Official Site",
    description:
      "Presidential Moon Rocks is the official site to explore the product collection and find licensed retailers carrying it. For adults 21+ where legal.",
    h1: "Official Presidential Cannabis",
    keywords: [
      "presidential thc",
      "official presidential thc",
      "presidential cannabis",
      "presidential moon rocks",
      "presidential pre-rolls",
      "presidential blunts",
    ],
    schema: ["Organization", "WebSite", "WebPage"],
    requiredData: ["company_entity", "approved_assets", "seo_metadata", "claims"],
    requiredApprovals: [
      "executive canonical host lock",
      "client/legal Presidential THC language approval",
      "metadata approval",
      "content approval",
    ],
    blocks: [],
    linksTo: [
      "/moon-rocks",
      "/moon-pods",
      "/orbit",
      "/our-story",
      "/learn",
      "/find-us",
      "/contact",
    ],
    sourceArtifact:
      "04-route-seo-matrix.csv; 20-presidential-seo-doctrine.md",
    notes:
      "Tier-0 entity recapture route. Planned here, not sitemap eligible until scaffold, metadata, content, and approval gates pass.",
    isMandatory: true,
  },
  {
    id: "moon-rocks",
    path: "/moon-rocks",
    kind: "product_platform",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 5,
    changeFrequency: "weekly",
    canonicalPath: "/moon-rocks",
    title: "Presidential Moon Rocks | Infused Pre-Rolls and Blunts",
    description:
      "Explore the Presidential Moon Rocks product platform. Availability varies by licensed retailer.",
    h1: "Presidential Moon Rocks",
    keywords: [
      "presidential moon rocks",
      "moon rock pre-rolls",
      "moon rock prerolls",
      "moon rock blunts",
      "infused pre-rolls",
      "infused blunts",
    ],
    schema: ["WebPage", "BreadcrumbList", "Product"],
    requiredData: [
      "product_platforms",
      "product_series",
      "products",
      "claims",
      "assets",
      "seo_metadata",
    ],
    requiredApprovals: [
      "product facts approval",
      "asset approval",
      "claim approval",
      "compliance review",
      "schema approval",
    ],
    blocks: [],
    linksTo: [
      "/moon-rocks/silver",
      "/moon-rocks/gold",
      "/moon-rocks/rose-gold",
      "/learn/[guide]",
      "/find-us",
    ],
    sourceArtifact:
      "04-route-seo-matrix.csv; 05-keyword-intent-map.csv; 06-schema-map.csv",
    notes:
      "Flagship product platform. Product schema is informational-only. Commerce fields are permanently excluded under the billboard-only site law.",
    isMandatory: true,
    isPublicPillar: true,
  },
  {
    id: "moon-pods",
    path: "/moon-pods",
    kind: "product_platform",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 4,
    changeFrequency: "weekly",
    canonicalPath: "/moon-pods",
    title: "Presidential Moon Pods",
    description:
      "Explore Presidential Moon Pods as a public-approved Presidential product pillar. Availability varies by licensed retailer.",
    h1: "Presidential Moon Pods",
    keywords: [
      "presidential moon pods",
      "presidential pods",
      "moon pods",
      "liquid diamonds pods",
    ],
    schema: ["WebPage", "BreadcrumbList"],
    requiredData: [
      "product_platforms",
      "product_catalog",
      "claims",
      "assets",
      "seo_metadata",
    ],
    requiredApprovals: [
      "product facts approval",
      "asset approval",
      "claim approval",
      "compliance review",
      "schema approval",
    ],
    blocks: [],
    linksTo: ["/orbit", "/learn/[guide]", "/find-us"],
    sourceArtifact:
      "04-route-seo-matrix.csv; 05-keyword-intent-map.csv; 20-presidential-seo-doctrine.md",
    notes:
      "Public-approved pillar, but gated until product facts, assets, claims, and compliance proof are ready.",
    isMandatory: true,
    isPublicPillar: true,
  },
  {
    id: "orbit",
    path: "/orbit",
    kind: "technology_platform",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 4,
    changeFrequency: "weekly",
    canonicalPath: "/orbit",
    title: "Presidential Orbit",
    description:
      "Explore Presidential Orbit as a public-approved Presidential technology platform. Public copy remains source-backed and compliance checked.",
    h1: "Presidential Orbit",
    keywords: [
      "presidential orbit",
      "orbit cannabis device",
      "orbit by presidential",
      "extract heat",
    ],
    schema: ["WebPage", "BreadcrumbList"],
    requiredData: [
      "product_platforms",
      "technology_proof",
      "claims",
      "assets",
      "seo_metadata",
    ],
    requiredApprovals: [
      "technology facts approval",
      "asset approval",
      "claim approval",
      "compliance review",
      "schema approval",
    ],
    blocks: [],
    linksTo: ["/moon-pods", "/learn/[guide]", "/find-us"],
    sourceArtifact:
      "04-route-seo-matrix.csv; 05-keyword-intent-map.csv; 20-presidential-seo-doctrine.md",
    notes:
      "Public-approved pillar, but gated until product/technology proof and compliance review pass.",
    isMandatory: true,
    isPublicPillar: true,
  },
  {
    id: "vapes",
    path: "/vapes",
    kind: "product_platform",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 4,
    changeFrequency: "weekly",
    canonicalPath: "/vapes",
    title: "Presidential Vapes | Moon Pods & Orbit Vape Platforms",
    description:
      "Explore Presidential Vapes, Moon Pods, Orbit hardware, vape cartridge education, and the official path to licensed retailers carrying Presidential products.",
    h1: "VAPES",
    keywords: [
      "presidential vapes",
      "how to judge a vape cartridge",
      "cannabis vape cartridge hardware",
      "live resin vs distillate vape",
      "vape cartridge terpenes",
      "vape cartridge testing",
      "moon pods",
      "orbit vape hardware",
    ],
    schema: ["WebPage", "BreadcrumbList"],
    requiredData: [
      "product_platforms",
      "product_catalog",
      "claims",
      "assets",
      "seo_metadata",
    ],
    requiredApprovals: [
      "product facts approval",
      "asset approval",
      "claim approval",
      "compliance review",
      "schema approval",
    ],
    blocks: [],
    linksTo: ["/moon-pods", "/orbit", "/learn", "/find-us"],
    sourceArtifact: "Owner requests 3389-SPUD and 9956-SPUD",
    notes:
      "Public-approved Vapes platform and educational page. General cartridge education does not assert unapproved Presidential product specifications.",
    isPublicPillar: true,
  },
  {
    id: "our-story",
    path: "/our-story",
    kind: "brand_story",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 5,
    changeFrequency: "monthly",
    canonicalPath: "/our-story",
    title: "Our Story | Presidential Moon Rocks",
    description:
      "Learn the official story behind Presidential and Moon Rocks through source-backed company facts.",
    h1: "The Presidential Story",
    keywords: [
      "presidential cannabis history",
      "presidential cannabis founders",
      "presidential brand heritage",
      "presidential origin story",
    ],
    schema: ["AboutPage", "WebPage", "BreadcrumbList"],
    requiredData: ["company_entity", "founder_story", "proof_items", "assets"],
    requiredApprovals: [
      "founder/company proof approval",
      "claim approval",
      "content approval",
      "compliance review",
    ],
    blocks: [],
    linksTo: ["/moon-rocks", "/learn", "/find-us"],
    sourceArtifact:
      "04-route-seo-matrix.csv; 20-presidential-seo-doctrine.md",
    notes:
      "Credibility route for entity proof. Claims must be source-backed before indexability.",
    isMandatory: true,
  },
  {
    id: "about",
    path: "/about",
    kind: "brand_story",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 4,
    changeFrequency: "monthly",
    canonicalPath: "/about",
    title: "About Presidential | Premium Infused Cannabis Brand",
    description:
      "Meet Presidential, the premium infused cannabis brand behind Moon Rocks, three signature series, and the Presidential Infusion System™. Explore the standard.",
    h1: "BUILT BETTER. ON PURPOSE.",
    keywords: [
      "presidential cannabis company",
      "premium infused cannabis brand",
      "presidential infusion system",
      "presidential moon rocks brand",
      "presidential silver gold rose gold series",
      "official presidential cannabis brand",
    ],
    schema: ["Organization", "WebPage", "BreadcrumbList"],
    requiredData: [
      "company_entity",
      "approved_about_copy",
      "approved_assets",
      "seo_metadata",
    ],
    requiredApprovals: [
      "metadata approval",
      "schema approval",
      "content approval",
      "asset approval",
      "compliance review",
    ],
    blocks: [],
    linksTo: [
      "/moon-rocks",
      "/moon-rocks/presidential-line-nino-brown",
      "/moon-rocks/cherry-gelato",
      "/our-story",
      "/find-us",
    ],
    sourceArtifact:
      "05-keyword-intent-map.csv; Owner request 3396-SPUD; Owner request 5518-SPUD",
    notes:
      "Company-intent route for who Presidential is, what it makes, and the standard behind the brand. Heritage and founder intent remain owned by /our-story; product/category intent remains owned by /moon-rocks. The route stays noindex and sitemap-excluded until publication approval.",
    isMandatory: true,
  },
  {
    id: "learn",
    path: "/learn",
    kind: "learn_hub",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 4,
    changeFrequency: "weekly",
    canonicalPath: "/learn",
    title: "Learn | Presidential Moon Rocks",
    description:
      "Explore official Presidential guides to Moon Rocks, infused pre-rolls, live resin, live rosin, and liquid diamonds.",
    h1: "Learn Presidential",
    keywords: [
      "moon rocks education",
      "infused cannabis guide",
      "live resin",
      "live rosin",
      "liquid diamonds",
    ],
    schema: ["WebPage", "BreadcrumbList", "ItemList"],
    requiredData: ["learn_articles", "assets", "seo_metadata"],
    requiredApprovals: [
      "article model approval",
      "content approval",
      "compliance review",
    ],
    blocks: [],
    linksTo: ["/learn/[guide]", "/moon-rocks", "/moon-pods", "/orbit", "/find-us"],
    sourceArtifact:
      "04-route-seo-matrix.csv; 05-keyword-intent-map.csv; 06-schema-map.csv",
    notes:
      "Education hub. Must avoid medical/effect claims and cite approved article records.",
    isMandatory: true,
  },
  {
    id: "learn-guide",
    path: "/learn/[guide]",
    kind: "learn_article",
    status: "conditional",
    indexability: "conditional_index",
    sitemap: "conditional",
    priority: 4,
    changeFrequency: "monthly",
    canonicalPath: "/learn/[guide]",
    title: "[Guide Title] | Presidential Learn",
    description:
      "A concise official Presidential guide to approved cannabis education topics.",
    h1: "[Guide Title]",
    keywords: [
      "what are moon rocks",
      "what are infused pre-rolls",
      "what is live resin",
      "what is live rosin",
      "what are liquid diamonds",
      "different extracts need different heat",
    ],
    schema: ["Article", "BreadcrumbList"],
    requiredData: ["learn_articles", "claims", "assets", "seo_metadata"],
    requiredApprovals: [
      "approved article record",
      "content approval",
      "compliance review",
      "schema approval",
    ],
    blocks: [
      "learn_content_approval",
      "content_approval",
      "compliance_review",
      "schema_approval",
    ],
    linksTo: ["/learn", "/moon-rocks", "/find-us"],
    sourceArtifact:
      "04-route-seo-matrix.csv; 05-keyword-intent-map.csv; 06-schema-map.csv",
    notes:
      "Template route. Generated only from approved article records with unique useful content.",
    isMandatory: true,
  },
  {
    id: "find-us",
    path: "/find-us",
    kind: "store_locator",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 5,
    changeFrequency: "daily",
    canonicalPath: "/find-us",
    title: "Find Presidential Near You | Official Retailer Locator",
    description:
      "Find licensed retailers that carry Presidential products. Availability varies by licensed retailer.",
    h1: "Find Presidential Near You",
    keywords: [
      "where to buy Presidential Moon Rocks",
      "Presidential near me",
      "Presidential retailers",
      "dispensaries with Presidential",
    ],
    schema: ["WebPage", "BreadcrumbList", "ItemList"],
    requiredData: ["stores", "store_availability", "seo_metadata"],
    requiredApprovals: [
      "verified store data source",
      "availability disclaimer approval",
      "compliance review",
    ],
    blocks: [],
    linksTo: ["/find-us/[state]", "/contact", "/moon-rocks"],
    sourceArtifact:
      "04-route-seo-matrix.csv; 05-keyword-intent-map.csv; 06-schema-map.csv",
    notes:
      "Native first-party locator route. Not sitemap eligible until verified store data exists.",
    isMandatory: true,
  },
  {
    id: "dispensaries-redirect",
    path: "/dispensaries",
    kind: "redirect",
    status: "conditional",
    indexability: "not_published",
    sitemap: "exclude",
    priority: 0,
    changeFrequency: "never",
    canonicalPath: "/find-us",
    title: "Find Presidential Near You",
    description:
      "Canonical redirect to the official Presidential retailer locator.",
    h1: "Find Presidential Near You",
    keywords: [],
    schema: [],
    requiredData: [],
    requiredApprovals: ["canonical redirect verification"],
    blocks: ["metadata_approval"],
    linksTo: ["/find-us"],
    sourceArtifact:
      "src/app/dispensaries/page.tsx; 2026-07-28 rendered route audit",
    notes:
      "Permanent legacy alias. It is part of the rendered route surface but never emits a document, schema, or sitemap entry.",
  },
  {
    id: "contact",
    path: "/contact",
    kind: "contact",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 4,
    changeFrequency: "monthly",
    canonicalPath: "/contact",
    title: "Contact Presidential | Official Presidential Moon Rocks",
    description:
      "Contact the official Presidential team for customer care, wholesale, press, or brand inquiries.",
    h1: "Contact Presidential",
    keywords: [
      "presidential contact",
      "presidential cannabis contact",
      "wholesale presidential",
      "presidential support",
    ],
    schema: ["ContactPage", "WebPage", "BreadcrumbList"],
    requiredData: ["company_entity", "official_contact_details", "seo_metadata"],
    requiredApprovals: ["official contact details approval", "content approval"],
    blocks: [],
    linksTo: ["/find-us", "/our-story"],
    sourceArtifact:
      "04-route-seo-matrix.csv; 20-presidential-seo-doctrine.md",
    notes:
      "Trust and contact route. Contact facts must be official before publication.",
    isMandatory: true,
  },
  {
    id: "official-presidential",
    path: "/official-presidential",
    kind: "brand_story",
    status: "planned",
    indexability: "conditional_index",
    sitemap: "conditional",
    priority: 5,
    changeFrequency: "monthly",
    canonicalPath: "/official-presidential",
    title: "Official Presidential | Presidential Cannabis",
    description:
      "The official home of Presidential. Find authentic Presidential cannabis products at licensed retailers.",
    h1: "Official Presidential",
    keywords: [
      "presidential thc",
      "official presidential thc",
      "official presidential",
      "presidential cannabis co",
    ],
    schema: ["WebPage", "BreadcrumbList"],
    requiredData: ["company_entity", "proof_items", "claims", "seo_metadata"],
    requiredApprovals: [
      "client/legal Presidential THC language approval",
      "founder/company proof approval",
      "metadata approval",
      "content approval",
      "compliance review",
    ],
    blocks: [
      "legal_presidential_thc",
      "founder_company_proof",
      "metadata_approval",
      "content_approval",
      "compliance_review",
    ],
    linksTo: ["/", "/our-story", "/moon-rocks", "/find-us"],
    sourceArtifact: "17-brand-defense-serp-keyword-addendum.md",
    notes:
      "Tier-0 brand-recapture route for Presidential THC confusion resolution. Planning-only registry record; page shell deferred, never indexable or sitemap eligible until legal and source-record publication gates pass.",
  },
  {
    id: "pre-rolls",
    path: "/pre-rolls",
    kind: "product_platform",
    status: "conditional",
    indexability: "conditional_index",
    sitemap: "conditional",
    priority: 4,
    changeFrequency: "weekly",
    canonicalPath: "/pre-rolls",
    title: "Presidential Pre-Rolls | Infused Pre-Rolls",
    description:
      "Explore Presidential pre-rolls and infused pre-rolls. Availability varies by licensed retailer.",
    h1: "Presidential Pre-Rolls",
    keywords: [
      "presidential pre-rolls",
      "presidential prerolls",
      "presidential infused pre-rolls",
      "infused pre-rolls",
    ],
    schema: ["WebPage", "BreadcrumbList", "ItemList"],
    requiredData: [
      "product_platforms",
      "product_catalog",
      "claims",
      "assets",
      "seo_metadata",
    ],
    requiredApprovals: [
      "category naming confirmation",
      "product facts approval",
      "asset approval",
      "claim approval",
      "compliance review",
      "schema approval",
    ],
    blocks: [
      "product_catalog",
      "product_assets",
      "product_claims",
      "compliance_review",
      "schema_approval",
    ],
    linksTo: ["/moon-rocks", "/learn", "/find-us"],
    sourceArtifact: "17-brand-defense-serp-keyword-addendum.md",
    notes:
      "Planning-only brand-defense category route for Presidential pre-roll searches. Standalone /pre-rolls versus /moon-rocks/pre-rolls remains a client/catalog decision; never indexable or sitemap eligible until source-record publication gates pass.",
  },
  {
    id: "blunts",
    path: "/blunts",
    kind: "product_platform",
    status: "conditional",
    indexability: "conditional_index",
    sitemap: "conditional",
    priority: 4,
    changeFrequency: "weekly",
    canonicalPath: "/blunts",
    title: "Presidential Blunts | Moon Rock Blunts",
    description:
      "Explore Presidential blunts and Moon Rock blunts. Availability varies by licensed retailer.",
    h1: "Presidential Blunts",
    keywords: [
      "presidential blunts",
      "presidential moon rock blunt",
      "presidential mini blunts",
      "infused blunts",
    ],
    schema: ["WebPage", "BreadcrumbList", "ItemList"],
    requiredData: [
      "product_platforms",
      "product_catalog",
      "claims",
      "assets",
      "seo_metadata",
    ],
    requiredApprovals: [
      "category naming confirmation",
      "product facts approval",
      "asset approval",
      "claim approval",
      "compliance review",
      "schema approval",
    ],
    blocks: [
      "product_catalog",
      "product_assets",
      "product_claims",
      "compliance_review",
      "schema_approval",
    ],
    linksTo: ["/moon-rocks", "/learn", "/find-us"],
    sourceArtifact: "17-brand-defense-serp-keyword-addendum.md",
    notes:
      "Planning-only brand-defense category route for Presidential blunt searches. Standalone /blunts versus /moon-rocks/blunts remains a client/catalog decision; never indexable or sitemap eligible until source-record publication gates pass.",
  },
  {
    id: "moon-rocks-silver",
    path: "/moon-rocks/silver",
    kind: "product_series",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 4,
    changeFrequency: "weekly",
    canonicalPath: "/moon-rocks/silver",
    title: "Presidential Silver Moon Rocks",
    description:
      "Explore the Presidential Silver Moon Rocks series after catalog and compliance approval.",
    h1: "Silver Flavor Series",
    keywords: ["presidential silver moon rocks", "moon rock flavors"],
    schema: ["WebPage", "BreadcrumbList", "ItemList"],
    requiredData: ["product_series", "products", "claims", "assets"],
    requiredApprovals: [
      "series facts approval",
      "asset approval",
      "compliance review",
    ],
    blocks: [],
    linksTo: ["/moon-rocks", "/moon-rocks/gold", "/moon-rocks/rose-gold", "/find-us"],
    sourceArtifact: "04-route-seo-matrix.csv",
    notes: "Conditional series route. Publish only from approved series records.",
  },
  {
    id: "moon-rocks-gold",
    path: "/moon-rocks/gold",
    kind: "product_series",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 4,
    changeFrequency: "weekly",
    canonicalPath: "/moon-rocks/gold",
    title: "Presidential Gold Moon Rocks",
    description:
      "Explore the Presidential Gold Moon Rocks series after catalog and compliance approval.",
    h1: "Gold Strain Series",
    keywords: ["presidential gold moon rocks", "live resin moon rocks"],
    schema: ["WebPage", "BreadcrumbList", "ItemList"],
    requiredData: ["product_series", "products", "claims", "assets"],
    requiredApprovals: [
      "series facts approval",
      "asset approval",
      "compliance review",
    ],
    blocks: [],
    linksTo: [
      "/moon-rocks",
      "/moon-rocks/silver",
      "/moon-rocks/rose-gold",
      "/find-us",
    ],
    sourceArtifact: "04-route-seo-matrix.csv",
    notes: "Conditional series route. Publish only from approved series records.",
  },
  {
    id: "moon-rocks-rose-gold",
    path: "/moon-rocks/rose-gold",
    kind: "product_series",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 4,
    changeFrequency: "weekly",
    canonicalPath: "/moon-rocks/rose-gold",
    title: "Presidential Rose Gold Moon Rocks",
    description:
      "Explore the Presidential Rose Gold Moon Rocks series after catalog and compliance approval.",
    h1: "Rose Gold Connoisseur Series",
    keywords: ["presidential rose gold moon rocks", "live rosin moon rocks"],
    schema: ["WebPage", "BreadcrumbList", "ItemList"],
    requiredData: ["product_series", "products", "claims", "assets"],
    requiredApprovals: [
      "series facts approval",
      "asset approval",
      "compliance review",
    ],
    blocks: [],
    linksTo: ["/moon-rocks", "/moon-rocks/silver", "/moon-rocks/gold", "/find-us"],
    sourceArtifact: "04-route-seo-matrix.csv",
    notes: "Conditional series route. Publish only from approved series records.",
  },
  {
    id: "moon-rocks-presidential-line",
    path: "/moon-rocks/presidential-line",
    kind: "product_series",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 4,
    changeFrequency: "weekly",
    canonicalPath: "/moon-rocks/presidential-line",
    title: "Presidential Line | Presidential Moon Rocks",
    description: "Explore the Presidential Line. Availability varies by licensed retailer.",
    h1: "Presidential Line",
    keywords: ["presidential line", "presidential moon rocks"],
    schema: ["WebPage", "BreadcrumbList", "ItemList"],
    requiredData: ["product_series", "products", "claims", "assets"],
    requiredApprovals: [
      "series facts approval",
      "asset approval",
      "compliance review",
    ],
    blocks: [],
    linksTo: ["/moon-rocks", "/find-us"],
    sourceArtifact:
      "src/lib/catalog/series-registry.ts; 2026-07-28 rendered route audit",
    notes: "Conditional series route. Publish only from approved series records.",
  },
  {
    id: "moon-rocks-presidential-house-line",
    path: "/moon-rocks/presidential-house-line",
    kind: "product_series",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 4,
    changeFrequency: "weekly",
    canonicalPath: "/moon-rocks/presidential-house-line",
    title: "Presidential House Line | Presidential Moon Rocks",
    description:
      "Explore the original Presidential formats. Availability varies by licensed retailer.",
    h1: "Presidential House Line",
    keywords: ["presidential house line", "presidential moon rocks"],
    schema: ["WebPage", "BreadcrumbList", "ItemList"],
    requiredData: ["product_series", "products", "claims", "assets"],
    requiredApprovals: [
      "series facts approval",
      "asset approval",
      "compliance review",
    ],
    blocks: [],
    linksTo: ["/moon-rocks", "/find-us"],
    sourceArtifact:
      "src/lib/catalog/series-registry.ts; 2026-07-28 rendered route audit",
    notes: "Conditional series route. Publish only from approved series records.",
  },
  {
    id: "moon-rocks-presidential-x-thc-design",
    path: "/moon-rocks/presidential-x-thc-design",
    kind: "product_series",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 4,
    changeFrequency: "weekly",
    canonicalPath: "/moon-rocks/presidential-x-thc-design",
    title: "Presidential x THC Design | Presidential Moon Rocks",
    description:
      "Explore the Presidential x THC Design series. Availability varies by licensed retailer.",
    h1: "Presidential x THC Design",
    keywords: ["presidential x thc design", "presidential moon rocks"],
    schema: ["WebPage", "BreadcrumbList", "ItemList"],
    requiredData: ["product_series", "products", "claims", "assets"],
    requiredApprovals: [
      "series facts approval",
      "asset approval",
      "compliance review",
    ],
    blocks: [],
    linksTo: ["/moon-rocks", "/find-us"],
    sourceArtifact:
      "src/lib/catalog/series-registry.ts; 2026-07-28 rendered route audit",
    notes: "Conditional series route. Publish only from approved series records.",
  },
  {
    id: "moon-rocks-product-detail",
    path: "/moon-rocks/[product-or-strain]",
    kind: "product_detail",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 3,
    changeFrequency: "weekly",
    canonicalPath: "/moon-rocks/[product-or-strain]",
    title: "[Product Name] | Presidential Moon Rocks",
    description:
      "Learn approved product facts for a Presidential Moon Rocks product. Availability varies by licensed retailer.",
    h1: "[Product Name]",
    keywords: ["presidential moon rocks product", "moon rock product"],
    schema: ["WebPage", "BreadcrumbList", "Product"],
    requiredData: ["products", "assets", "claims", "seo_metadata"],
    requiredApprovals: [
      "unique approved product record",
      "product facts approval",
      "asset approval",
      "compliance review",
      "schema approval",
    ],
    blocks: [],
    linksTo: ["/moon-rocks", "/find-us"],
    sourceArtifact:
      "04-route-seo-matrix.csv; 06-schema-map.csv; 21-presidential-seo-doctrine-rule-matrix.md",
    notes:
      "Dynamic product route. Generated only if it has unique, useful, approved product content. Product schema remains informational.",
  },
  {
    id: "find-us-state",
    path: "/find-us/[state]",
    kind: "state_locator",
    status: "approved",
    indexability: "index_follow",
    sitemap: "include",
    priority: 4,
    changeFrequency: "daily",
    canonicalPath: "/find-us/[state]",
    title: "Find Presidential in [State] | Licensed Retailers",
    description:
      "Find licensed retailers carrying Presidential products in an approved state. Availability varies by licensed retailer.",
    h1: "Find Presidential in [State]",
    keywords: ["presidential moon rocks [state]", "where to buy presidential [state]"],
    schema: ["WebPage", "BreadcrumbList", "ItemList"],
    requiredData: ["stores", "store_availability", "seo_metadata"],
    requiredApprovals: [
      "verified state store data",
      "state legal review",
      "compliance review",
    ],
    blocks: [],
    linksTo: ["/find-us", "/find-us/[state]/[city]", "/moon-rocks"],
    sourceArtifact:
      "04-route-seo-matrix.csv; 05-keyword-intent-map.csv",
    notes:
      "State locator route. Generated only when verified store data and state review gates pass.",
  },
  {
    id: "find-us-city",
    path: "/find-us/[state]/[city]",
    kind: "city_locator",
    status: "conditional",
    indexability: "conditional_index",
    sitemap: "conditional",
    priority: 3,
    changeFrequency: "daily",
    canonicalPath: "/find-us/[state]/[city]",
    title: "Find Presidential in [City], [State] | Licensed Retailers",
    description:
      "Find licensed retailers carrying Presidential products in an approved city. Availability varies by licensed retailer.",
    h1: "Find Presidential in [City]",
    keywords: ["presidential moon rocks [city]", "where to buy presidential [city]"],
    schema: ["WebPage", "BreadcrumbList", "ItemList"],
    requiredData: ["stores", "store_availability", "seo_metadata"],
    requiredApprovals: [
      "verified city store data",
      "state legal review",
      "compliance review",
    ],
    blocks: ["verified_store_data", "state_legal_review", "compliance_review"],
    linksTo: ["/find-us", "/find-us/[state]", "/find-us/[state]/[city]/[retailer]"],
    sourceArtifact: "04-route-seo-matrix.csv",
    notes:
      "City locator route. Generated only when unique local value and verified store data exist.",
  },
  {
    id: "find-us-retailer-detail",
    path: "/find-us/[state]/[city]/[retailer]",
    kind: "retailer_detail",
    status: "conditional",
    indexability: "conditional_index",
    sitemap: "conditional",
    priority: 2,
    changeFrequency: "daily",
    canonicalPath: "/find-us/[state]/[city]/[retailer]",
    title: "Presidential at [Retailer] | Licensed Retailer",
    description:
      "See verified retailer information for Presidential products at an approved licensed retailer.",
    h1: "Presidential at [Retailer]",
    keywords: ["presidential at [retailer]", "[retailer] presidential moon rocks"],
    schema: ["WebPage", "BreadcrumbList", "LocalBusiness"],
    requiredData: ["stores", "store_availability", "retailer_authorization"],
    requiredApprovals: [
      "unique verified retailer facts",
      "retailer authorization",
      "LocalBusiness schema legal review",
      "compliance review",
    ],
    blocks: [
      "verified_store_data",
      "retailer_authorization",
      "state_legal_review",
      "compliance_review",
      "schema_approval",
    ],
    linksTo: ["/find-us", "/find-us/[state]", "/find-us/[state]/[city]", "/moon-rocks"],
    sourceArtifact:
      "04-route-seo-matrix.csv; 06-schema-map.csv; 21-presidential-seo-doctrine-rule-matrix.md",
    notes:
      "Retailer detail route. Must not imply Presidential owns independent retailers.",
  },
  {
    id: "loyalty",
    path: "/loyalty",
    kind: "future_module",
    status: "future",
    indexability: "not_published",
    sitemap: "exclude",
    priority: 1,
    canonicalPath: "/loyalty",
    title: "Rock Club Loyalty Prototype | Presidential",
    description:
      "Preview the Presidential Rock Club verification and loyalty experience.",
    h1: "Scan. Verify. Ascend.",
    keywords: ["presidential loyalty", "presidential rewards"],
    schema: ["WebPage"],
    requiredData: ["program_rules", "compliance_policy"],
    requiredApprovals: ["future module approval", "compliance review"],
    blocks: ["future_module_approval", "not_phase_1", "compliance_review"],
    linksTo: [],
    sourceArtifact: "04-route-seo-matrix.csv; 35-route-registry-seo-source-of-truth-architecture.md",
    notes: "Future module placeholder. Excluded from sitemap and publication.",
  },
  {
    id: "admin",
    path: "/admin",
    kind: "private_system",
    status: "private",
    indexability: "noindex",
    sitemap: "exclude",
    priority: 0,
    canonicalPath: "/admin",
    title: "Admin",
    description: "Private internal route placeholder.",
    h1: "Admin",
    keywords: [],
    schema: [],
    requiredData: [],
    requiredApprovals: ["private internal route"],
    blocks: ["private_internal"],
    linksTo: [],
    sourceArtifact: "35-route-registry-seo-source-of-truth-architecture.md",
    notes: "Private route family. Never sitemap eligible.",
  },
  {
    id: "api",
    path: "/api",
    kind: "private_system",
    status: "private",
    indexability: "not_published",
    sitemap: "exclude",
    priority: 0,
    canonicalPath: "/api",
    title: "API",
    description: "API route family placeholder.",
    h1: "API",
    keywords: [],
    schema: [],
    requiredData: [],
    requiredApprovals: ["private internal route"],
    blocks: ["private_internal"],
    linksTo: [],
    sourceArtifact: "35-route-registry-seo-source-of-truth-architecture.md",
    notes: "API route family. Never sitemap eligible.",
  },
  {
    id: "preview",
    path: "/preview",
    kind: "private_system",
    status: "private",
    indexability: "noindex",
    sitemap: "exclude",
    priority: 0,
    canonicalPath: "/preview",
    title: "Preview",
    description: "Private preview route placeholder.",
    h1: "Preview",
    keywords: [],
    schema: [],
    requiredData: [],
    requiredApprovals: ["private internal route"],
    blocks: ["private_internal"],
    linksTo: [],
    sourceArtifact: "35-route-registry-seo-source-of-truth-architecture.md",
    notes: "Preview route family. Never sitemap eligible.",
  },
  {
    id: "drafts",
    path: "/drafts",
    kind: "private_system",
    status: "private",
    indexability: "noindex",
    sitemap: "exclude",
    priority: 0,
    canonicalPath: "/drafts",
    title: "Drafts",
    description: "Private drafts route placeholder.",
    h1: "Drafts",
    keywords: [],
    schema: [],
    requiredData: [],
    requiredApprovals: ["private internal route"],
    blocks: ["private_internal"],
    linksTo: [],
    sourceArtifact: "35-route-registry-seo-source-of-truth-architecture.md",
    notes: "Draft route family. Never sitemap eligible.",
  },
  {
    id: "internal-threat-research",
    path: "/internal-threat-research",
    kind: "private_system",
    status: "blocked",
    indexability: "noindex",
    sitemap: "exclude",
    priority: 0,
    canonicalPath: "/internal-threat-research",
    title: "Internal Research",
    description: "Internal-only research placeholder.",
    h1: "Internal Research",
    keywords: [],
    schema: [],
    requiredData: [],
    requiredApprovals: ["private internal route"],
    blocks: ["private_internal"],
    linksTo: [],
    sourceArtifact: "20-presidential-seo-doctrine.md; 21-presidential-seo-doctrine-rule-matrix.md",
    notes:
      "Threat research is internal-only and must never become a public SEO surface.",
  },
] as const satisfies readonly SeoRouteRecord[];

export type MandatoryRoutePath = (typeof MANDATORY_ROUTE_PATHS)[number];
export type RegisteredRoute = (typeof ROUTE_REGISTRY)[number];
