export const draftSitePageFixtures = {
  "moon-rocks": {
    _id: "local.cms-shaped.site-page.moon-rocks.fixture",
    _type: "sitePage",
    title: "Moon Rocks",
    slug: "moon-rocks",
    routePhase: "draft_preview_only",
    summary: "CMS-shaped Moon Rocks draft fixture for private module rendering while live draft reads are disabled.",
    modules: [
      {
        _key: "moon-rocks-hero",
        _type: "heroBlock",
        eyebrow: "Presidential platform",
        headline: "Moon Rocks",
        description: "A private preview of the flagship product platform module sequence.",
        moduleControl: {
          internalLabel: "Moon Rocks Hero",
          componentKey: "hero",
          renderEligibility: "draft_preview_only",
          sortIntent: 10,
        },
      },
      {
        _key: "moon-rocks-platform",
        _type: "productPlatformBlock",
        heading: "Flagship platform",
        description: "Product story, source proof, formats, and media evidence stay separated until approved.",
        facts: [
          { label: "Route", value: "/moon-rocks", publicUseStatus: "private_preview" },
          { label: "Status", value: "CMS draft", publicUseStatus: "not_public" },
        ],
        moduleControl: {
          internalLabel: "Moon Rocks Platform",
          componentKey: "product_platform",
          renderEligibility: "draft_preview_only",
          sortIntent: 20,
        },
      },
      {
        _key: "moon-rocks-product-rail",
        _type: "productRailBlock",
        heading: "Candidate product rail",
        description: "Preview cards for product/media mapping before client approval.",
        cards: [
          { title: "Original Moon Rocks", route: "/moon-rocks", sourceStatus: "candidate" },
          { title: "Product media candidates", sourceStatus: "pending review", routeGate: "private" },
          { title: "Source proof packet", sourceStatus: "internal evidence", routeGate: "private" },
        ],
        moduleControl: {
          internalLabel: "Moon Rocks Product Rail",
          componentKey: "product_rail",
          renderEligibility: "draft_preview_only",
          sortIntent: 30,
        },
      },
      {
        _key: "moon-rocks-asset-proof",
        _type: "assetProofBlock",
        heading: "Asset proof",
        description: "Asset records remain candidates until source, rights, and client approval are complete.",
        proofType: "asset_review",
        proofSource: "client/source intake",
        approvalStatus: "pending_review",
        provenanceStatus: "candidate_evidence",
        allowedUsage: "private_review_only",
        moduleControl: {
          internalLabel: "Moon Rocks Asset Proof",
          componentKey: "asset_proof",
          renderEligibility: "draft_preview_only",
          sortIntent: 40,
        },
      },
    ],
  },
  "moon-pods": {
    _id: "local.cms-shaped.site-page.moon-pods.fixture",
    _type: "sitePage",
    title: "Moon Pods",
    slug: "moon-pods",
    routePhase: "draft_preview_only",
    summary: "CMS-shaped Moon Pods draft fixture for private module rendering while live draft reads are disabled.",
    modules: [
      {
        _key: "moon-pods-hero",
        _type: "heroBlock",
        eyebrow: "Presidential platform",
        headline: "Moon Pods",
        description: "A private preview of flavor, format, and product education modules.",
        moduleControl: {
          internalLabel: "Moon Pods Hero",
          componentKey: "hero",
          renderEligibility: "draft_preview_only",
          sortIntent: 10,
        },
      },
      {
        _key: "moon-pods-platform",
        _type: "productPlatformBlock",
        heading: "Flavor-forward product lane",
        description: "Moon Pods content can combine product education, format clarity, and approved media.",
        relatedProductLinks: [
          { name: "Orbit", slug: "orbit", positioningLine: "Connected product system" },
        ],
        moduleControl: {
          internalLabel: "Moon Pods Platform",
          componentKey: "product_platform",
          renderEligibility: "draft_preview_only",
          sortIntent: 20,
        },
      },
      {
        _key: "moon-pods-guide",
        _type: "learnGuideBlock",
        heading: "Learn module",
        description: "Draft guide cards can connect product education without making unsupported claims.",
        featuredGuides: [
          { title: "What is live resin?", slug: "what-is-live-resin", guideTopic: "Extract education" },
          { title: "Different extracts need different heat", slug: "different-extracts-need-different-heat", guideTopic: "Format education" },
        ],
        moduleControl: {
          internalLabel: "Moon Pods Learn Module",
          componentKey: "learn_guide",
          renderEligibility: "draft_preview_only",
          sortIntent: 30,
        },
      },
    ],
  },
  orbit: {
    _id: "local.cms-shaped.site-page.orbit.fixture",
    _type: "sitePage",
    title: "Orbit",
    slug: "orbit",
    routePhase: "draft_preview_only",
    summary: "CMS-shaped Orbit draft fixture for private module rendering while live draft reads are disabled.",
    modules: [
      {
        _key: "orbit-hero",
        _type: "heroBlock",
        eyebrow: "Presidential platform",
        headline: "Orbit",
        description: "A private preview of the Orbit platform story and related product modules.",
        moduleControl: {
          internalLabel: "Orbit Hero",
          componentKey: "hero",
          renderEligibility: "draft_preview_only",
          sortIntent: 10,
        },
      },
      {
        _key: "orbit-timeline",
        _type: "timelineBlock",
        heading: "Orbit story path",
        events: [
          { label: "Platform definition", dateOrSequence: "Step 1" },
          { label: "Product relationship", dateOrSequence: "Step 2" },
          { label: "Media and proof review", dateOrSequence: "Step 3" },
        ],
        moduleControl: {
          internalLabel: "Orbit Timeline",
          componentKey: "timeline",
          renderEligibility: "draft_preview_only",
          sortIntent: 20,
        },
      },
      {
        _key: "orbit-platform",
        _type: "productPlatformBlock",
        heading: "Orbit platform",
        description: "Orbit can render as its own CMS product-platform lane while device facts, product relationship, and direct media stay under review.",
        relatedProductLinks: [
          { name: "Moon Pods", slug: "moon-pods", positioningLine: "Connected product lane" },
        ],
        moduleControl: {
          internalLabel: "Orbit Platform",
          componentKey: "product_platform",
          renderEligibility: "draft_preview_only",
          sortIntent: 30,
        },
      },
    ],
  },
  "our-story": {
    _id: "local.cms-shaped.site-page.our-story.fixture",
    _type: "sitePage",
    title: "Our Story",
    slug: "our-story",
    routePhase: "draft_preview_only",
    summary: "CMS-shaped Our Story draft fixture for private module rendering while live draft reads are disabled.",
    modules: [
      {
        _key: "our-story-hero",
        _type: "heroBlock",
        headline: "Our Story",
        description: "A private preview of brand story modules and source-proof structure.",
        moduleControl: {
          internalLabel: "Our Story Hero",
          componentKey: "hero",
          renderEligibility: "draft_preview_only",
          sortIntent: 10,
        },
      },
      {
        _key: "our-story-proof",
        _type: "storyProofBlock",
        heading: "Story proof",
        description: "Story claims need source and approval before public use.",
        proofType: "story_review",
        approvalStatus: "pending_review",
        moduleControl: {
          internalLabel: "Story Proof",
          componentKey: "story_proof",
          renderEligibility: "draft_preview_only",
          sortIntent: 20,
        },
      },
    ],
  },
  learn: {
    _id: "local.cms-shaped.site-page.learn.fixture",
    _type: "sitePage",
    title: "Learn",
    slug: "learn",
    routePhase: "draft_preview_only",
    summary: "CMS-shaped Learn hub draft fixture for private module rendering while live draft reads are disabled.",
    modules: [
      {
        _key: "learn-hero",
        _type: "heroBlock",
        headline: "Learn",
        description: "A private preview of the education hub and guide cards.",
        moduleControl: {
          internalLabel: "Learn Hero",
          componentKey: "hero",
          renderEligibility: "draft_preview_only",
          sortIntent: 10,
        },
      },
      {
        _key: "learn-guide-hub",
        _type: "guideHubBlock",
        heading: "Guide hub",
        featuredGuides: [
          { title: "What are Moon Rocks?", slug: "what-are-moon-rocks", guideTopic: "Product education" },
          { title: "Flavor science", slug: "flavor-science", guideTopic: "Flavor education" },
          { title: "Infusion science", slug: "infusion-science", guideTopic: "Process education" },
        ],
        moduleControl: {
          internalLabel: "Learn Guide Hub",
          componentKey: "guide_hub",
          renderEligibility: "draft_preview_only",
          sortIntent: 20,
        },
      },
    ],
  },
  "find-us": {
    _id: "local.cms-shaped.site-page.find-us.fixture",
    _type: "sitePage",
    title: "Find Us",
    slug: "find-us",
    routePhase: "draft_preview_only",
    summary: "CMS-shaped Find Us draft fixture for private module rendering while live draft reads are disabled.",
    modules: [
      {
        _key: "find-us-hero",
        _type: "heroBlock",
        headline: "Find Presidential",
        description: "A private preview of the retailer/locator shell before verified retailer data is approved.",
        moduleControl: {
          internalLabel: "Find Us Hero",
          componentKey: "hero",
          renderEligibility: "draft_preview_only",
          sortIntent: 10,
        },
      },
      {
        _key: "find-us-locator",
        _type: "locatorShellBlock",
        heading: "Licensed retailer discovery",
        description: "The locator module remains a shell until verified retailer records are ready.",
        formIntent: "retailer_locator",
        moduleControl: {
          internalLabel: "Locator Shell",
          componentKey: "locator_shell",
          renderEligibility: "draft_preview_only",
          sortIntent: 20,
        },
      },
    ],
  },
  contact: {
    _id: "local.cms-shaped.site-page.contact.fixture",
    _type: "sitePage",
    title: "Contact",
    slug: "contact",
    routePhase: "draft_preview_only",
    summary: "CMS-shaped Contact draft fixture for private module rendering while live draft reads are disabled.",
    modules: [
      {
        _key: "contact-hero",
        _type: "heroBlock",
        headline: "Contact Presidential",
        description: "A private preview of contact intent modules and routing.",
        moduleControl: {
          internalLabel: "Contact Hero",
          componentKey: "hero",
          renderEligibility: "draft_preview_only",
          sortIntent: 10,
        },
      },
      {
        _key: "contact-form-intent",
        _type: "contactBlock",
        heading: "Contact routing",
        description: "Contact modules can separate general, retailer, media, and partnership intent.",
        formIntent: "general_contact",
        moduleControl: {
          internalLabel: "Contact Form Intent",
          componentKey: "contact",
          renderEligibility: "draft_preview_only",
          sortIntent: 20,
        },
      },
    ],
  },
} as const;
