export type BluntArtwork = {
  readonly id: string;
  readonly name: string;
  readonly edition: string;
  readonly description: string;
  readonly src: `/media/blunts/${string}.webp`;
  readonly alt: string;
  readonly shape: "portrait" | "square";
};

export const BLUNT_ARTWORKS = [
  { id: "cereal-milk-title", name: "Cereal Milk", edition: "Title artwork", description: "Cream, cereal forms, and bright blue accents sweep across an orange field beneath the oversized Cereal Milk title.", src: "/media/blunts/cereal-milk-title.webp", alt: "Cereal Milk Presidential Moon Rock Blunt title graphic with cream and cereal artwork", shape: "portrait" },
  { id: "cereal-milk", name: "Cereal Milk", edition: "Clean artwork", description: "The clean edition removes the large title so the package and flowing orange, cream, and blue composition carry the frame.", src: "/media/blunts/cereal-milk.webp", alt: "Cereal Milk Presidential Moon Rock Blunt clean package graphic", shape: "portrait" },
  { id: "apricotti", name: "Apricotti", edition: "Collaboration artwork", description: "Apricot halves, pale gold liquid forms, and green palm leaves surround the soft-toned collaboration package.", src: "/media/blunts/apricotti.webp", alt: "Apricotti Presidential collaboration Moon Rock Blunt graphic with apricots and palm leaves", shape: "square" },
  { id: "blue-dream", name: "Blue Dream", edition: "Collection artwork", description: "Blue Dream rises above sculpted clouds, palms, and a flock of distant birds in a clear sky-blue scene.", src: "/media/blunts/blue-dream.webp", alt: "Blue Dream Presidential Moon Rock Blunt graphic with blue clouds and palms", shape: "portrait" },
  { id: "blue-raspberry", name: "Blue Raspberry", edition: "Collection artwork", description: "Blue and red berry forms orbit metallic leaves and liquid ribbons around the cobalt package.", src: "/media/blunts/blue-raspberry.webp", alt: "Blue Raspberry Presidential Moon Rock Blunt graphic with berries and metallic leaves", shape: "square" },
  { id: "cap-junky", name: "Cap Junky", edition: "Trendi collaboration artwork", description: "A cactus, faceted teal stones, and dark liquid curves create a desert-night stage for Cap Junky.", src: "/media/blunts/cap-junky.webp", alt: "Cap Junky Presidential and Trendi Moon Rock Blunt graphic with cactus and teal stones", shape: "portrait" },
  { id: "cherry-gelato", name: "Cherry Gelato", edition: "Rove collaboration artwork", description: "Glossy cherries, a waffle-cone form, and mint-colored liquid shapes frame the red Cherry Gelato package.", src: "/media/blunts/cherry-gelato.webp", alt: "Cherry Gelato Presidential and Rove Moon Rock Blunt graphic with cherries and cone artwork", shape: "square" },
  { id: "crescendo", name: "Crescendo", edition: "Collaboration artwork", description: "Purple and blue plumes expand into a field of musical notes around the lavender Crescendo package.", src: "/media/blunts/crescendo.webp", alt: "Crescendo Presidential collaboration Moon Rock Blunt graphic with colorful musical notes", shape: "square" },
  { id: "daniel-larusso", name: "Daniel LaRusso", edition: "Collaboration artwork", description: "A blue dragon, crossed sword, and dark liquid base give Daniel LaRusso a bold martial-arts composition.", src: "/media/blunts/daniel-larusso.webp", alt: "Daniel LaRusso Presidential collaboration Moon Rock Blunt graphic with dragon and sword", shape: "square" },
  { id: "galactic-gas", name: "Galactic Gas", edition: "Collection artwork", description: "A luminous moon and flowing cyan-and-magenta terrain turn Galactic Gas into a vivid planetary poster.", src: "/media/blunts/galactic-gas.webp", alt: "Galactic Gas Presidential Moon Rock Blunt graphic with moon and neon planetary artwork", shape: "portrait" },
  { id: "garlic-cookies", name: "Garlic Cookies", edition: "Clean artwork", description: "Silver garlic forms and green highlights move across a black background around the geometric collaboration pack.", src: "/media/blunts/garlic-cookies.webp", alt: "Garlic Cookies Presidential collaboration Moon Rock Blunt clean graphic", shape: "square" },
  { id: "garlic-cookies-announcement", name: "Garlic Cookies", edition: "Announcement artwork", description: "The supplied announcement edition adds the Garlic Cookies title and Coming Soon treatment to the silver-and-green composition.", src: "/media/blunts/garlic-cookies-announcement.webp", alt: "Garlic Cookies Presidential collaboration announcement graphic with Coming Soon title", shape: "square" },
  { id: "ghost-haze-train", name: "Ghost Haze Train", edition: "Collaboration artwork", description: "A silver locomotive cuts through liquid metal beneath a full moon, framed by the black-and-green package.", src: "/media/blunts/ghost-haze-train.webp", alt: "Ghost Haze Train Presidential collaboration Moon Rock Blunt graphic with train and moon", shape: "square" },
  { id: "gorilla-goo", name: "Gorilla Goo", edition: "Collection artwork", description: "Purple palms, glossy droplets, and a stylized gorilla surround the black Gorilla Goo package.", src: "/media/blunts/gorilla-goo.webp", alt: "Gorilla Goo Presidential Moon Rock Blunt graphic with purple palms and gorilla artwork", shape: "portrait" },
  { id: "grape", name: "Grape", edition: "Collection artwork", description: "Grape clusters and violet liquid ribbons sweep around the magenta pack on a pale lavender field.", src: "/media/blunts/grape.webp", alt: "Grape Presidential Moon Rock Blunt graphic with grapes and violet ribbons", shape: "square" },
  { id: "king-louis", name: "King Louis", edition: "Collaboration artwork", description: "King Louis stands before a pale moon, profile portrait, and ornate red flourishes with the title anchored below.", src: "/media/blunts/king-louis.webp", alt: "King Louis Presidential Moon Rock Blunt graphic with moon and ornate red artwork", shape: "portrait" },
  { id: "laura-charles", name: "Laura Charles", edition: "Collaboration artwork", description: "Disco balls, stereo speakers, musical notes, and purple liquid shapes build a full music-stage composition.", src: "/media/blunts/laura-charles.webp", alt: "Laura Charles Presidential collaboration Moon Rock Blunt graphic with disco balls and speakers", shape: "square" },
  { id: "nino-brown", name: "Nino Brown", edition: "Collaboration artwork", description: "A gold city skyline, heavy chain forms, and deep teal clouds surround the dark Nino Brown package.", src: "/media/blunts/nino-brown.webp", alt: "Nino Brown Presidential collaboration Moon Rock Blunt graphic with gold skyline and chains", shape: "square" },
  { id: "nyc-diesel", name: "NYC Diesel", edition: "Collection artwork", description: "A moonlit New York skyline rises through green and gold cloud forms beneath the NYC Diesel title.", src: "/media/blunts/nyc-diesel.webp", alt: "NYC Diesel Presidential Moon Rock Blunt graphic with New York skyline and full moon", shape: "portrait" },
  { id: "orange-push-pop", name: "Orange Push Pop", edition: "Trendi collaboration artwork", description: "Orange and teal frozen-bar forms radiate around the collaboration pack above an oversized title treatment.", src: "/media/blunts/orange-push-pop.webp", alt: "Orange Push Pop Presidential and Trendi Moon Rock Blunt graphic with orange and teal frozen forms", shape: "portrait" },
  { id: "papaya-punch", name: "Papaya Punch", edition: "Collection artwork", description: "Papaya, citrus, tropical leaves, and orange ribbons form a bright botanical frame around the package.", src: "/media/blunts/papaya-punch.webp", alt: "Papaya Punch Presidential Moon Rock Blunt graphic with papaya and tropical leaves", shape: "portrait" },
  { id: "peach-mango", name: "Peach Mango", edition: "Collection artwork", description: "Soft peach fruit, dark palm fronds, and metallic spheres create a warm sculptural arrangement.", src: "/media/blunts/peach-mango.webp", alt: "Peach Mango Presidential Moon Rock Blunt graphic with peach fruit and palm leaves", shape: "square" },
  { id: "pineapple", name: "Pineapple", edition: "Collection artwork", description: "Golden pineapples and teal leaves emerge through green-and-yellow liquid forms around the bright package.", src: "/media/blunts/pineapple.webp", alt: "Pineapple Presidential Moon Rock Blunt graphic with pineapples and teal leaves", shape: "square" },
  { id: "pink-cookies-clean", name: "Pink Cookies", edition: "Clean artwork", description: "Cookie forms, pink-and-bronze ribbons, and small metallic spheres frame the magenta package on a rose field.", src: "/media/blunts/pink-cookies-clean.webp", alt: "Pink Cookies Presidential Moon Rock Blunt clean graphic with cookie forms and pink ribbons", shape: "square" },
  { id: "pink-cookies-title", name: "Pink Cookies", edition: "Title artwork", description: "The title edition adds the large Pink Cookies name beneath the package while preserving the rose-toned composition.", src: "/media/blunts/pink-cookies-title.webp", alt: "Pink Cookies Presidential Moon Rock Blunt title graphic", shape: "portrait" },
  { id: "presidential-og", name: "Presidential OG", edition: "Signature artwork", description: "A teal classic car, Los Angeles skyline, and metallic wave forms create a polished city portrait.", src: "/media/blunts/presidential-og.webp", alt: "Presidential OG Moon Rock Blunt graphic with Los Angeles skyline and classic car", shape: "square" },
  { id: "rainbow-belts", name: "Rainbow Belts", edition: "Collection artwork", description: "Multicolor ribbon forms arc across a dark lunar scene around the deep red package and bold title.", src: "/media/blunts/rainbow-belts.webp", alt: "Rainbow Belts Presidential Moon Rock Blunt graphic with multicolor ribbons and moon", shape: "portrait" },
  { id: "sfv-og", name: "SFV OG", edition: "Collection artwork", description: "A warm gold sky, distant palms, and teal cloud forms lift the SFV OG package above a floating cityscape.", src: "/media/blunts/sfv-og.webp", alt: "SFV OG Presidential Moon Rock Blunt graphic with golden sky and floating cityscape", shape: "portrait" },
  { id: "skywalker", name: "Skywalker", edition: "Rove collaboration artwork", description: "Asteroids, a large moon, metallic equipment, and liquid silver shapes create a deep-space mechanical world.", src: "/media/blunts/skywalker.webp", alt: "Skywalker Presidential and Rove Moon Rock Blunt graphic with moon, asteroids, and machinery", shape: "square" },
  { id: "strawberry", name: "Strawberry", edition: "Collection artwork", description: "Strawberries, palms, teal liquid arcs, and a pale moon surround the red Strawberry package.", src: "/media/blunts/strawberry.webp", alt: "Strawberry Presidential Moon Rock Blunt graphic with strawberries, palms, and moon", shape: "square" },
  { id: "tropical", name: "Tropical", edition: "Collection artwork", description: "A curling wave, palms, flowers, and a warm horizon create a coastal frame for the blue Tropical pack.", src: "/media/blunts/tropical.webp", alt: "Tropical Presidential Moon Rock Blunt graphic with wave, palms, and flowers", shape: "square" },
  { id: "watermelon", name: "Watermelon", edition: "Collection artwork", description: "Watermelon slices and red-and-teal liquid forms surround the coral package against a soft pink field.", src: "/media/blunts/watermelon.webp", alt: "Watermelon Presidential Moon Rock Blunt graphic with watermelon and liquid forms", shape: "square" },
  { id: "waui", name: "Waui", edition: "Rove collaboration artwork", description: "Purple flowers, tropical leaves, and violet liquid shapes expand around the orange-and-purple Waui package.", src: "/media/blunts/waui.webp", alt: "Waui Presidential and Rove Moon Rock Blunt graphic with purple flowers and tropical leaves", shape: "square" },
  { id: "whoa-si-whoa", name: "Whoa Si Whoa", edition: "Collaboration artwork", description: "Gold laurel branches, dark teal waves, and trophy-style details give Whoa Si Whoa a ceremonial frame.", src: "/media/blunts/whoa-si-whoa.webp", alt: "Whoa Si Whoa Presidential collaboration Moon Rock Blunt graphic with gold laurel branches", shape: "square" },
  { id: "xj-13", name: "XJ-13", edition: "Collaboration artwork", description: "Gold leaf forms and molecular linework rise through teal liquid shapes around the pale XJ-13 package.", src: "/media/blunts/xj-13.webp", alt: "XJ-13 Presidential collaboration Moon Rock Blunt graphic with gold leaves and molecular artwork", shape: "portrait" },
  { id: "xxx", name: "XXX", edition: "Collection artwork", description: "Planets, lemon forms, and dark teal waves place the black XXX package inside a gold-and-blue solar scene.", src: "/media/blunts/xxx.webp", alt: "XXX Presidential Moon Rock Blunt graphic with planets, lemon forms, and teal waves", shape: "portrait" },
  { id: "head-cheese", name: "Head Cheese", edition: "Collaboration artwork", description: "A pale moon, gold diamond forms, and layered teal-and-gold clouds frame the Head Cheese package and title.", src: "/media/blunts/head-cheese.webp", alt: "Head Cheese Presidential collaboration Moon Rock Blunt graphic with moon and gold diamond forms", shape: "portrait" },
  { id: "cosmic-cookies", name: "Cosmic Cookies", edition: "Clean artwork", description: "Violet nebulae, bright blue arcs, and dark celestial textures form a dense universe around the package.", src: "/media/blunts/cosmic-cookies.webp", alt: "Cosmic Cookies Presidential Moon Rock Blunt clean graphic with violet nebula artwork", shape: "portrait" },
  { id: "cosmic-cookies-title", name: "Cosmic Cookies", edition: "Title artwork", description: "The title edition adds a sharp Cosmic Cookies lockup to the violet-and-blue celestial composition.", src: "/media/blunts/cosmic-cookies-title.webp", alt: "Cosmic Cookies Presidential Moon Rock Blunt title graphic", shape: "portrait" },
  { id: "wedding-cake", name: "Wedding Cake", edition: "Clean artwork", description: "Layered cake forms, cream textures, violet accents, and teal ribbons build a bright yellow celebration scene.", src: "/media/blunts/wedding-cake.webp", alt: "Wedding Cake Presidential Moon Rock Blunt clean graphic with layered cake artwork", shape: "portrait" },
  { id: "wedding-cake-title", name: "Wedding Cake", edition: "Title artwork", description: "The title edition adds the large Wedding Cake name across the same yellow, violet, cream, and teal artwork.", src: "/media/blunts/wedding-cake-title.webp", alt: "Wedding Cake Presidential Moon Rock Blunt title graphic", shape: "portrait" },
] as const satisfies readonly BluntArtwork[];
