export type BluntArtwork = {
  readonly id: string;
  readonly name: string;
  readonly edition: string;
  readonly description: string;
  readonly src: `/media/blunts/${string}.webp`;
  readonly alt: string;
  readonly shape: "portrait" | "square";
};

export const BLUNT_ARTWORKS = [
  { id: "cereal-milk-title", name: "Cereal Milk", edition: "1.5g infused blunt · Flower · Live rosin · Diamonds", description: "Cereal Milk brings a creamy strain profile known for sweet milk and vanilla notes to Presidential's live-rosin infusion. Flower, live rosin, and diamonds make this a choice for connoisseurs who want the rosin recipe in a finished roll. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/cereal-milk-title.webp", alt: "Presidential Cereal Milk 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "apricotti", name: "Apricotti", edition: "1.5g infused blunt · Flower · Live resin · Kief", description: "Apricotti pairs cannabis flower with Moxie live resin and a kief finish. The collaboration is made for consumers who want an extract-led Moon Rock recipe, with the character of live resin alongside the flower. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/apricotti.webp", alt: "Presidential Apricotti 1.5g Moon Rock blunt product", shape: "square" },
  { id: "blue-dream", name: "Blue Dream", edition: "1.5g infused blunt · Flower · Live resin · Diamonds", description: "Blue Dream's familiar blueberry character meets earthy pine in this flower, live resin, and diamonds combination. It is a natural pick for people who enjoy berry notes with a recognizable cannabis finish. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/blue-dream.webp", alt: "Presidential Blue Dream 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "blue-raspberry", name: "Blue Raspberry", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Blue Raspberry puts its namesake berry flavor at the front of Presidential's flower, distillate, and kief recipe. Choose it when you want a fruit-flavored Moon Rock with the substance of infused cannabis flower. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/blue-raspberry.webp", alt: "Presidential Blue Raspberry 1.5g Moon Rock blunt product", shape: "square" },
  { id: "cap-junky", name: "Cap Junky", edition: "1.5g infused blunt · Flower · Live resin · Diamonds", description: "Cap Junky brings a gassy strain profile with citrus zest and pine to the Presidential and Trendi collaboration. Flower infused with liquid live resin and finished with diamonds gives fuel-and-citrus fans a ready-rolled way to explore this selection. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/cap-junky.webp", alt: "Presidential Cap Junky 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "cherry-gelato", name: "Cherry Gelato", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Cherry Gelato pairs a sweet cherry and creamy Gelato profile with Presidential's Rove collaboration. Cannabis flower, distillate, and kief bring the infusion, making this a selection for people drawn to fruit with a rounded, creamy character. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/cherry-gelato.webp", alt: "Presidential Cherry Gelato 1.5g Moon Rock blunt product", shape: "square" },
  { id: "crescendo", name: "Crescendo", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Crescendo combines THC Design flower with distillate and kief. Its reported strain profile moves from earthy diesel into berry and citrus, offering a more layered choice for people who like fruit alongside a gassy finish. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/crescendo.webp", alt: "Presidential Crescendo 1.5g Moon Rock blunt product", shape: "square" },
  { id: "daniel-larusso", name: "Daniel LaRusso", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Daniel LaRusso starts with indoor flower from Ball Family Farms, then adds Presidential's distillate infusion and kief finish. Pungent earth and mint aromas, with reported herbal and pepper notes, make this a fit for fans of assertive cannabis character. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/daniel-larusso.webp", alt: "Presidential Daniel LaRusso 1.5g Moon Rock blunt product", shape: "square" },
  { id: "galactic-gas", name: "Galactic Gas", edition: "1.5g infused blunt · Flower · Live resin · Diamonds", description: "Galactic Gas is for the fuel-and-spice enthusiast: its strain profile is reported as pungent gas, pine, and spicy herbs. Flower, live resin, and diamonds bring that named selection into Presidential's infused Moon Rock format. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/galactic-gas.webp", alt: "Presidential Galactic Gas 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "garlic-cookies", name: "Garlic Cookies", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Garlic Cookies brings Nature's Chemistry flower together with distillate and kief. Its savory garlic, earthy, and diesel profile makes it a distinctive choice for consumers who prefer pungent cannabis over fruit-forward selections. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/garlic-cookies.webp", alt: "Presidential Garlic Cookies 1.5g Moon Rock blunt product", shape: "square" },
  { id: "ghost-haze-train", name: "Ghost Train Haze", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Ghost Train Haze combines Nature's Chemistry flower with distillate and a kief finish. Reported citrus, pine, and spice give this Haze selection its appeal to people who favor sharp, herbal cannabis aromas. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/ghost-haze-train.webp", alt: "Presidential Ghost Train Haze 1.5g Moon Rock blunt product", shape: "square" },
  { id: "gorilla-goo", name: "Gorilla Goo", edition: "1.5g infused blunt · Flower · Live resin · Distillate · Diamonds", description: "Gorilla Goo's reported sour fuel, pine, and chocolate notes give it a rich, gassy character. This version combines flower, live resin, distillate, and diamonds for consumers who want a layered infusion around that robust strain profile. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/gorilla-goo.webp", alt: "Presidential Gorilla Goo 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "grape", name: "Grape", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Grape brings a grape-led flavor to Presidential's flower, distillate, and kief combination. It is a straightforward choice for people who want a recognizable fruit flavor in a prepared Moon Rock roll. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/grape.webp", alt: "Presidential Grape 1.5g Moon Rock blunt product", shape: "square" },
  { id: "king-louis", name: "King Louis", edition: "1.5g infused blunt · Flower · Live resin · Diamonds", description: "King Louis leans into the classic OG profile: pine, lemon, earth, and a pronounced fuel note. Flower infused with live resin and finished with diamonds makes it a selection for consumers who appreciate a traditional kush character. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/king-louis.webp", alt: "Presidential King Louis 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "laura-charles", name: "Laura Charles", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Laura Charles brings Ball Family Farms flower into Presidential's distillate-and-kief recipe. The grower describes creamy floral flavor with spice on the finish, giving it a distinctive place for people who enjoy fragrant, nuanced cannabis. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/laura-charles.webp", alt: "Presidential Laura Charles 1.5g Moon Rock blunt product", shape: "square" },
  { id: "nino-brown", name: "Nino Brown", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Nino Brown pairs Ball Family Farms flower with distillate and kief. The grower's creamy, gassy aroma description makes this a compelling option for people who want rich cannabis character in a finished infused blunt. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/nino-brown.webp", alt: "Presidential Nino Brown 1.5g Moon Rock blunt product", shape: "square" },
  { id: "nyc-diesel", name: "NYC Diesel", edition: "1.5g infused blunt · Flower · Live resin · Diamonds", description: "NYC Diesel brings grapefruit-like citrus and unmistakable fuel notes to flower infused with live resin and finished with diamonds. Choose it for the contrast between a bright citrus nose and a deeper diesel character. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/nyc-diesel.webp", alt: "Presidential NYC Diesel 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "orange-push-pop", name: "Orange Push Pop", edition: "1.5g infused blunt · Flower · Live resin · Diamonds", description: "Orange Push Pop combines Trendi flower, liquid live resin, and diamonds. Its reported creamy citrus profile makes this collaboration a match for consumers who enjoy rounded orange notes with their infused flower. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/orange-push-pop.webp", alt: "Presidential Orange Push Pop 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "papaya-punch", name: "Papaya Punch", edition: "1.5g infused blunt · Flower · Live resin · Diamonds", description: "Papaya Punch brings a tropical fruit and berry profile to flower infused with live resin and finished with diamonds. This is the selection for people who gravitate toward juicy fruit character while still wanting Presidential's layered cannabis construction. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/papaya-punch.webp", alt: "Presidential Papaya Punch 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "peach-mango", name: "Peach Mango", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Peach Mango brings together ripe peach and mango flavor in Presidential's flower, distillate, and kief recipe. Its tropical fruit character suits consumers who want a distinctly fruity infused roll. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/peach-mango.webp", alt: "Presidential Peach Mango 1.5g Moon Rock blunt product", shape: "square" },
  { id: "pineapple", name: "Pineapple", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Pineapple centers the namesake tropical fruit flavor over cannabis flower infused with distillate and finished with kief. A fruit-led choice for consumers who like pineapple character in a ready-rolled Moon Rock. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/pineapple.webp", alt: "Presidential Pineapple 1.5g Moon Rock blunt product", shape: "square" },
  { id: "pink-cookies-title", name: "Pink Cookies", edition: "1.5g infused blunt · Flower · Live resin · Distillate · Diamonds", description: "Pink Cookies is associated with a sweet vanilla profile balanced by earth and citrus. This version brings together flower, live resin, distillate, and diamonds for consumers who enjoy creamy strain character with a layered infusion. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/pink-cookies-title.webp", alt: "Presidential Pink Cookies 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "presidential-og", name: "Presidential (Classic)", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "The original Presidential selection pairs cannabis flower with distillate and kief. Its reported earthy, mint, and floral character makes Classic a useful starting point for consumers who want the house Moon Rock recipe. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/presidential-og.webp", alt: "Presidential Presidential (Classic) 1.5g Moon Rock blunt product", shape: "square" },
  { id: "rainbow-belts", name: "Rainbow Belts", edition: "1.5g infused blunt · Flower · Live resin · Diamonds", description: "Rainbow Belts balances sweet fruit and citrus with a diesel edge in its reported strain profile. Flower, live resin, and diamonds make it a choice for people who enjoy both fruity and gassy notes in the same selection. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/rainbow-belts.webp", alt: "Presidential Rainbow Belts 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "sfv-og", name: "SFV OG", edition: "1.5g infused blunt · Flower · Live resin · Diamonds", description: "SFV OG brings lemon, pine, and earthy diesel character to Presidential's live-resin-and-diamonds recipe. It is a selection for consumers who appreciate the resinous citrus-and-pine side of the OG family. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/sfv-og.webp", alt: "Presidential SFV OG 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "skywalker", name: "Skywalker", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Skywalker pairs cannabis flower with Rove-formulated distillate and a kief finish. Rove describes its Skywalker profile through blueberry, tropical, and earthy notes, giving this collaboration a fruit-and-earth character to explore. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/skywalker.webp", alt: "Presidential Skywalker 1.5g Moon Rock blunt product", shape: "square" },
  { id: "strawberry", name: "Strawberry", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Strawberry brings a sweet berry flavor to Presidential's flower, distillate, and kief recipe. Choose this fruit-forward selection when strawberry is the flavor you want in an infused roll. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/strawberry.webp", alt: "Presidential Strawberry 1.5g Moon Rock blunt product", shape: "square" },
  { id: "tropical", name: "Tropical", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Tropical is the tropical-flavored selection in Presidential's flower, distillate, and kief lineup. The cannabis is infused and prepared as a Moon Rock roll for consumers who enjoy fruit-led flavor with the convenience of a finished blunt. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/tropical.webp", alt: "Presidential Tropical 1.5g Moon Rock blunt product", shape: "square" },
  { id: "watermelon", name: "Watermelon", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Watermelon combines its namesake fruit flavor with cannabis flower, distillate, and kief. This is the melon-led option for consumers exploring the fruit-flavored side of the Presidential lineup. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/watermelon.webp", alt: "Presidential Watermelon 1.5g Moon Rock blunt product", shape: "square" },
  { id: "waui", name: "Waui", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Waui brings a pineapple-led tropical profile to the Presidential and Rove collaboration. Flower infused with Rove distillate and finished with kief makes it a choice for people who enjoy sweet tropical cannabis flavor. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/waui.webp", alt: "Presidential Waui 1.5g Moon Rock blunt product", shape: "square" },
  { id: "whoa-si-whoa", name: "Whoa Si Whoa", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "Whoa Si Whoa features Top Shelf Cultivation flower with sweet, earthy, and gassy strain character. Presidential adds distillate and kief, bringing this named cultivation partnership into a prepared Moon Rock blunt. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/whoa-si-whoa.webp", alt: "Presidential Whoa Si Whoa 1.5g Moon Rock blunt product", shape: "square" },
  { id: "xj-13", name: "XJ-13", edition: "1.5g infused blunt · Flower · Distillate · Kief", description: "XJ-13 pairs THC Design flower with distillate and kief. Its reported citrus, lemon, and pine profile makes this collaboration a selection for consumers who enjoy bright aromatics with an earthy cannabis base. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/xj-13.webp", alt: "Presidential XJ-13 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "xxx", name: "XXX", edition: "1.5g infused blunt · Flower · Live resin · Distillate · Diamonds", description: "XXX brings a woodsy citrus profile to an infused flower roll. The version shown combines live resin, distillate, and diamonds, offering consumers a layered concentrate recipe with a classic earthy cannabis character. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/xxx.webp", alt: "Presidential XXX 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "head-cheese", name: "Head Cheese", edition: "1.5g infused blunt · Flower · Live resin · Diamonds", description: "Head Cheese pairs Polaris cannabis with live resin and diamonds. Its reported pungent cheese aroma and notes of lemon and spice make this a distinctive choice for consumers who seek savory strain character. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/head-cheese.webp", alt: "Presidential Head Cheese 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "cosmic-cookies-title", name: "Cosmic Cookies", edition: "1.5g infused blunt · Flower · Live rosin · Diamonds", description: "Cosmic Cookies combines cannabis flower, live rosin, and diamonds in Presidential's Rose Gold selection. Its appeal is the recipe itself: a hybrid selection with a live-rosin infusion, prepared for consumers who want to explore the connoisseur side of Moon Rocks. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/cosmic-cookies-title.webp", alt: "Presidential Cosmic Cookies 1.5g Moon Rock blunt product", shape: "portrait" },
  { id: "wedding-cake-title", name: "Wedding Cake", edition: "1.5g infused blunt · Flower · Live rosin · Diamonds", description: "Wedding Cake brings a strain profile known for vanilla, sweetness, and earthy citrus to Presidential's Rose Gold recipe. Flower, live rosin, and diamonds make it a selection for people who enjoy creamy cannabis character and a rosin-based infusion. One 1.5g Moon Rock blunt, rolled in a tobacco-free wrap.", src: "/media/blunts/wedding-cake-title.webp", alt: "Presidential Wedding Cake 1.5g Moon Rock blunt product", shape: "portrait" },
] as const satisfies readonly BluntArtwork[];
